server:
  port: 9999
  servlet:
    context-path: /

jwt:
  secret: 6A576D5A7134743777217A25432A462D4A614E645267556B5870327235753878
  lifetime: 86400000

spring:
#  sql:
#    init:
#      mode: always
#      continue-on-error: true
  datasource:
    url: jdbc:postgresql://localhost:5432/diplom
    username: postgres
    password: knyazev0666

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update